# Generated by Django 5.2 on 2025-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('R', 'Required'), ('P', 'In Progress'), ('C', 'Completed')], default='R', max_length=1),
        ),
    ]
