# Generated by Django 5.2 on 2025-04-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_checklist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='issued_date',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='accountant',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='license',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Expiring'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
